//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaymanWoods.PersistenceLayer.Data.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPMaster
    {
        public long OTPMasterID { get; set; }
        public long UserID { get; set; }
        public string GUID { get; set; }
        public string OTP { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Attempts { get; set; }
    }
}
